name: Python CI with SonarCloud

on:
  push:
    branches: [ "main", "Amaury" ]
  pull_request:
    branches: [ "main", "Amaury" ]

jobs:
  build:
    name: Test and Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        export PYTHONPATH=$PYTHONPATH:./shipping_order_service:./driver_service:./routing_service:./tracking_service
        pytest \
          --cov=shipping_order_service \
          --cov=driver_service \
          --cov=routing_service \
          --cov=tracking_service \
          --cov-report=xml:coverage.xml \
          --cov-report=term

    - name: Check coverage file
      run: ls -l coverage.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
        SONAR_ORGANIZATION: ${{ secrets.ORGANIZATION }}
